##Numpy 
Conceitos básicos de manipulação de arrays e matrizes no numpy

In [1]:
#importando a biblioteca 
import numpy as np


In [2]:
#Criando um array de zeros
a = np.zeros(4) # array de 4 zeros
a

array([0., 0., 0., 0.])

Os arrays do numpy são parecidos com as listas exceto por duas coisas:


1.   Os arrays devem possuir os elementos de um mesmo tipo
2.   Esses tipos devem ser um dos dtypes fonecidos pelo numpy

Por default, o tipo do array é float64, mas podemos manipular e alterar

Obs.: Para casos de engenharia, numpy possui a forma complexa (dtype = csingle)


In [3]:
type(a[0])

numpy.float64

In [4]:
a = np.zeros(5,dtype=int)
print(a)
type(a[0])

[0 0 0 0 0]


numpy.int64

In [5]:
#dimensao
a.shape #não tem dimensão o array
#para criar a dimensão, só usar a.shape=(5,1)

(5,)

##Criando Arrays



*   np.linspace(a,b,c) cria um array do valor a até o valor b(com ambos inclusos) com c elementos. No exemplo tem um array  de 1 até 10 com 5 elementos variando de 1 a 10.
*   Os elementps entre a e b tem o mesmo intervalo entre um elemento do array e outro
*   Para criar um array na 'força bruta' usamos np.array([n1,n2])
*   Para criar uma matriz identidate usamos np.identity(n), com n o número de elementos na diagonal
* OBS.: Ao criar uma matriz  é necessário colocar cada linha em um colchete separado, além do colchete principal. Ex.: matriz 2x2---> colchete principal e u par de colchetes para cada linha dentro do colchete principal


In [6]:
ar_um_a_dez = np.linspace(1,10,5)
ar_um_a_dez


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [7]:
array_aleatorio = np.array([3,5])
array_aleatorio

array([3, 5])

In [8]:
#array 2x2
dois_dois = np.array([[1,2],[3,4]])
dois_dois

array([[1, 2],
       [3, 4]])

In [9]:
#matriz identidade 3x3
identidade_3 = np.array([[1,0,0],[0,1,0],[0,0,1]])
identidade_3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
identidade_5 = np.identity(5)
identidade_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Manipulação de arrays

In [11]:
#Escolhendo o primeiro elemento do array == mesma forma de manipulação de listas
array_aleatorio[0]

3

In [12]:
#Escolhendo a partir de um intervalo
ar_um_a_dez[0:2]

array([1.  , 3.25])

In [13]:
#Agora, com a matriz identidade
identidade_3[1,1]#linha dois, coluna 2(lembrar que o elemento inicial é zero)

1

In [14]:
#Para escolher uma linha, usamos o seguinte
identidade_3[1,:]

array([0, 1, 0])

In [15]:
#Escolhendo uma coluna
identidade_3[:,0]

array([1, 0, 0])

## Alguns métodos com arrays




*   Ordenação
*   Média
*   Máximo
*   Soma acumulada
*   Outros




In [16]:
#Criando meu array de exemplo
exemplo = np.array([2,3,5,7,1,4])

In [17]:
#Ordenação
exemplo.sort()
exemplo

array([1, 2, 3, 4, 5, 7])

In [18]:
#soma dos elementos do array
exemplo.sum()

22

In [19]:
#media
exemplo.mean()

3.6666666666666665

In [20]:
#maximo
exemplo.max()

7

In [21]:
#minimo
exemplo.min()

1

In [22]:
# soma cumulativa ( usado bastante em probabilidade)
exemplo.cumsum()

array([ 1,  3,  6, 10, 15, 22])

In [23]:
#produto cumulativo
exemplo.cumprod()

array([  1,   2,   6,  24, 120, 840])

In [24]:
#variancia
exemplo.var()

3.8888888888888893

In [25]:
#desvio padrao
exemplo.std()

1.9720265943665387

In [26]:
#Agora com uma matriz 2x2
exemplo2 = np.array([[1,2],[3,4]])
exemplo2.sum()# soma os elementos de toda a matriz

10

In [27]:
exemplo2[0].sum()#somando os elementos da primeira linha

3

In [28]:
exemplo2[:,0].sum()# simando os elementos da primeira coluna

4

## Operações aritimeticas

In [38]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c =np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])


In [30]:
#soma
a+b

array([ 6,  8, 10, 12])

In [31]:
#multiplicação
a*b

array([ 5, 12, 21, 32])

In [32]:
#divisão
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [41]:
#Operações são realizadas com formatos iguais
#Exemplo 1: a+c vai apresentar erro
a+c

ValueError: ignored

In [42]:
#Agora, c+d vai funcionar
c+d

array([[ 6,  8],
       [10, 12]])

In [43]:
#Operação com escalar tem uma forma diferente
a+ 5

array([6, 7, 8, 9])

In [44]:
#Independente da posição
c*5

array([[ 5, 10],
       [15, 20]])

##Multiplicando Matriz

* A multiplicação de matrizes é diferente da multiplicação dos elementos das matrizes
* Duas matrizes Amn e Bjk onde (m,j) são os números de linhas e (n,k) são os numeros de colunas
* A multiplicação entre A e B só acontecerá se o número de colunas em A for igual ao número de linhas em B
* A multiplicação entre A e B retornará uma matriz  C com  m linhas e k colunas  

In [45]:
#Para multiplicar matrizes utilizamos o comando @
c@d

array([[19, 22],
       [43, 50]])

In [46]:
#multiplicação de matriz é diferente de c*d. Observe:
c*d

array([[ 5, 12],
       [21, 32]])

In [49]:
#Multiplicando uma matriz 3x2 por uma 2x3

A1 = np.array([[1,2],[3,4],[5,6]])
B1 = np.array([[1,2,3],[4,5,6]])
C1 = np.array([[1,2,3,4],[5,6,7,8]])
A1@B1  #Gera uma matriz 3x3

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [48]:
B1@A1

array([[22, 28],
       [49, 64]])

In [50]:
A1@C1

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [59]:
# C1@A1 Vvai gerar um erro de dimensão. Para caber na regra, vou usar o transpose
C1.transpose()@A1.transpose()

array([[11, 23, 35],
       [14, 30, 46],
       [17, 37, 57],
       [20, 44, 68]])

##Broadcasting

No Broadcasting o numpy 'completa' dados para realizar uma operação


In [62]:
#Exemplo 1: uma matriz 3x3 somado a um vetor 1x3
#Vamos completar o vetor
a33 = np.ones((3,3))#preciso colocar o 3,3 entre parenteses para gerar a matriz
a33

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
a13 = np.array([1,2,3])

In [65]:
#note que a matriz 1x3 vai virar uma matriz 3x3 repetindo os elementos nas linhas 2 e 3
a33+a13

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [72]:
#Agora, com um vetor coluna(matriz 3x1)
#Acontece um preenchimento das colunas 2 e 3
a31 = np.array([[1],[2],[3]])
a33 + a31

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

## Determinantes, Inversas e Autovalores

In [76]:
#Lembrando da nossa matriz c 2x2
c

array([[1, 2],
       [3, 4]])

In [77]:
#Calculando o Determinante
np.linalg.det(c)


-2.0000000000000004

In [78]:
#Calculando a matriz inversa
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [79]:
#Calculando autovalores
np.linalg.eigvals(c)

array([-0.37228132,  5.37228132])

In [81]:
#Resolvendo o sistema linear Ax = b
#{ x+2y =1
#{3x + 5y = 2
a11 = np.array([[1,2],[3,5]])
b11 = np.array([1,2])
np.linalg.solve(a11,b11)

array([-1.,  1.])