## **NUMPY**

**Primeiros comandos**

In [0]:
#importando o numpy
import numpy as np

In [3]:
#Criando um array
a=np.array([2,5,7])
print(a)
a.dtype

[2 5 7]


dtype('int64')

In [4]:
#Outro array
b= np.array([[2,3,4],[5,6,7]])
b.ndim


2

In [5]:
#Podemos definir um array na hora da criação
#Criando um array complexo
comp_array=np.array([(2+1j,3),(5,6)], dtype=complex)
comp_array

array([[2.+1.j, 3.+0.j],
       [5.+0.j, 6.+0.j]])

In [6]:
#Criando um array de zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#Criando um array de número um
um_array= np.ones((4,7))
um_array

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [8]:
#Array de sequancia de números
seq_array = np.arange(1,50,6)
seq_array

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49])

**Analisando os arrays**


In [9]:
um_array.shape

(4, 7)

In [10]:
um_array.ndim

2

Operações

In [11]:
array_a = np.array([15,20,25,30])
array_b = np.array([10,10,10,10])
array_soma = array_a +array_b
array_soma

array([25, 30, 35, 40])

In [13]:
array_subtracao =array_a - array_b
array_subtracao

array([ 5, 10, 15, 20])

In [20]:
#Somando uma constante
array_a +=100
print(array_a) 

[315 320 325 330]


In [21]:
#Multiplicando por uma constante
array_b *=2
print(array_b)

[20 20 20 20]


**MATRIZ**

In [17]:
#Criando a primeira matriz
#Atenção!!! matriz precisa de 2 colchetes!!!
matriz_a = np.array([[2,3],[4,5]])
#Criando a segunda matriz ---> Identidade
matriz_b = np.array([[1,0],[0,1]])
#multiplicando cada elemento da matriz(i11a*i11b, i12a*112b...) ---> Não é multiplicação de matrizes
print("Multiplicação de cada elemento da matriz")
print(matriz_a*matriz_b)
#Multiplicação de matrizes
print("Multiplicando as matrizes")
print(matriz_a@matriz_b)
#Outra forma de fazer isso é utilizando o  seguinte
matriz_a.dot(matriz_b)

Multiplicação de cada elemento da matriz
[[2 0]
 [0 5]]
Multiplicando as matrizes
[[2 3]
 [4 5]]


array([[2, 3],
       [4, 5]])