## **NUMPY**

**Primeiros comandos**

In [0]:
#importando o numpy
import numpy as np

In [0]:
#Criando um array
a=np.array([2,5,7])
print(a)
a.dtype

[2 5 7]


dtype('int64')

In [0]:
#Outro array
b= np.array([[2,3,4],[5,6,7]])
b.ndim


2

In [0]:
#Podemos definir um array na hora da criação
#Criando um array complexo
comp_array=np.array([(2+1j,3),(5,6)], dtype=complex)
comp_array

array([[2.+1.j, 3.+0.j],
       [5.+0.j, 6.+0.j]])

In [0]:
#Criando um array de zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
#Criando um array de número um
um_array= np.ones((4,7))
um_array

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [0]:
#Array de sequancia de números
seq_array = np.arange(1,50,6)
seq_array

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49])

**Analisando os arrays**


In [0]:
um_array.shape

(4, 7)

In [0]:
um_array.ndim

2