# **PageRank**
Código explicando o funcionamento do algoritmo de ranqueamento do google - PageRank. Considerações iniciais:



*   4 páginas  com links - Google tem mais páginas,  mas a lógica é parecida
*   Cada página pode ter de um até três links para as outras páginas
*   A probabilidade de escolher qualquer uma das páginas no começo do algoritimo é a mesma para as 4 = 25%
*   Cada linha da matriz de transição representa as os links da página que eu estou para a página que dão acesso





In [ ]:
#Importando as bibliotecas Numpy e Pandas
#Não há necessidade de utilizar o Pandas, foi força do hábito mesmo
import numpy as np
import pandas as pd

## Funcionamento


*   Criamos a matriz de transição com cada linha representando os links
*   A soma de cada linha tem que ter valor igua a 1 = probabilidade total
*   Criamos um vetor chamado rank que é o ranking de cada página
*   Atualizamos o vetor de rank multiplicando pela matriz de transição transposta



In [ ]:
#criando a matriz de transição
matr = np.matrix([[0,1/3,1/3,1/3],[0,0,1/2,1/2],[1/2,0,0,1/2],[1,0,0,0]])
matr
#Criando a matriz transposta para multiplicar com o ranking
matriz = matr.transpose()
matriz

matrix([[0.        , 0.        , 0.5       , 1.        ],
        [0.33333333, 0.        , 0.        , 0.        ],
        [0.33333333, 0.5       , 0.        , 0.        ],
        [0.33333333, 0.5       , 0.5       , 0.        ]])

In [ ]:
#Criando o vetor rank
rank = np.matrix([0.25,0.25,0.25,0.25])
rank1 = rank.transpose()
rank1

matrix([[0.25],
        [0.25],
        [0.25],
        [0.25]])

In [ ]:
#Fazendo o loop do do pagerank
for x in range(100):
  rank1 = np.dot(matriz,rank1)
  print(rank1)

[[0.375     ]
 [0.08333333]
 [0.20833333]
 [0.33333333]]
[[0.4375    ]
 [0.125     ]
 [0.16666667]
 [0.27083333]]
[[0.35416667]
 [0.14583333]
 [0.20833333]
 [0.29166667]]
[[0.39583333]
 [0.11805556]
 [0.19097222]
 [0.29513889]]
[[0.390625  ]
 [0.13194444]
 [0.19097222]
 [0.28645833]]
[[0.38194444]
 [0.13020833]
 [0.19618056]
 [0.29166667]]
[[0.38975694]
 [0.12731481]
 [0.19241898]
 [0.29050926]]
[[0.38671875]
 [0.12991898]
 [0.19357639]
 [0.28978588]]
[[0.38657407]
 [0.12890625]
 [0.19386574]
 [0.29065394]]
[[0.38758681]
 [0.12885802]
 [0.19331115]
 [0.29024402]]
[[0.38689959]
 [0.1291956 ]
 [0.19362461]
 [0.29028019]]
[[0.3870925 ]
 [0.12896653]
 [0.19356433]
 [0.29037664]]
[[0.38715881]
 [0.12903083]
 [0.1935141 ]
 [0.29029626]]
[[0.38705331]
 [0.12905294]
 [0.19356835]
 [0.2903254 ]]
[[0.38710958]
 [0.12901777]
 [0.19354424]
 [0.29032841]]
[[0.38710053]
 [0.12903653]
 [0.19354541]
 [0.29031753]]
[[0.38709024]
 [0.12903351]
 [0.19355177]
 [0.29032448]]
[[0.38710037]
 [0.12903008]
 [0