# **TensorFlow - Tensores**
 O TensorFlow é uma biblioteca de computação numérica. Parecido com numpy, uma de suas diferenças é o suporte para GPU. O TensorFlow utiliza o conceito de tensores, que são parecidos com os famosos arrays do numpy com a diferença que o tf pode ter um único escalar. Poderiamos utilizar o keras para fazer modelos de DL, mas o tensorflow permite fazer alguns ajustes que o keras não consegue.

In [20]:
#Importando o TensorFlow
import tensorflow as tf
import numpy as np

In [3]:
#Criando o primeiro tensor. Observe que ele dá o formato(3x3)
tf.constant([[25,35,49],[18,19,20],[21,22,28]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 35, 49],
       [18, 19, 20],
       [21, 22, 28]], dtype=int32)>

In [6]:
#Criando o escalar
tf.constant(25)

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [10]:
tensor_1_flamengo_brasileiros= tf.constant([[80,82],[83,87],[92,2009],[19,20]])
#Observação: Coloquei 2009 pois o TensorFlow não aceita zero a esquerda
tensor_1_flamengo_brasileiros.shape

TensorShape([4, 2])

**Operações** **com** **Tensores**

In [17]:
tensor_1 = tf.constant([[1,2,3],[4,5,6]])
tensor_1 + 2
#ou
tf.add(tensor_1,10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [15]:
tf.square(tensor_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [18]:
tf.multiply(tensor_1,4)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  8, 12],
       [16, 20, 24]], dtype=int32)>

In [22]:
#TensorFlow consegue trabalhar bem com numpy
array_numpy= np.array([2,3,4])
b = tf.square(array_numpy)
b

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 4,  9, 16])>

In [27]:
#TensorFlow não consegue trabalhar com tipos de variáveis diferentes
#tf.constant(10.)+tf.constant(15) ---> Dá erro!!! Tirar do comentário e 
# O erro é proposital!! Para resolver, precisamos converter
tensor2 = tf.constant(50., dtype=tf.float64)
tf.constant(10.0) + tf.cast(tensor2, tf.float32)


<tf.Tensor: shape=(), dtype=float32, numpy=60.0>

In [29]:
#Variáveis. As variáveis podem ser alteradas.
variavel = tf.Variable([[10,11,12],[13,14,15]])
variavel.assign(10*variavel)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[100, 110, 120],
       [130, 140, 150]], dtype=int32)>